begin;

create extension if not exists pgcrypto;

do $$
begin
  create extension if not exists pg_cron;
exception
  when insufficient_privilege then
    raise notice 'pg_cron no se pudo crear en este entorno (permiso insuficiente).';
  when undefined_file then
    raise notice 'pg_cron no esta disponible en este entorno.';
end;
$$;

do $$
begin
  create extension if not exists pg_net;
exception
  when insufficient_privilege then
    raise notice 'pg_net no se pudo crear en este entorno (permiso insuficiente).';
  when undefined_file then
    raise notice 'pg_net no esta disponible en este entorno.';
end;
$$;

do $$
begin
  create type public.user_role as enum ('admin', 'operator');
exception
  when duplicate_object then null;
end;
$$;

do $$
begin
  create type public.session_status as enum ('active', 'completed', 'cancelled');
exception
  when duplicate_object then null;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role public.user_role not null default 'operator',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.atvs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  plate text unique,
  active boolean not null default true,
  base_minutes integer not null default 10 check (base_minutes > 0),
  base_price_cop integer not null default 10000 check (base_price_cop > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  atv_id uuid not null references public.atvs(id) on delete restrict,
  started_by uuid not null references auth.users(id) on delete restrict,
  started_at timestamptz not null default timezone('utc', now()),
  target_end_at timestamptz not null,
  ended_at timestamptz,
  status public.session_status not null default 'active',
  minutes_billed integer check (minutes_billed is null or minutes_billed >= 0),
  amount_cop integer check (amount_cop is null or amount_cop >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.sessions(id) on delete cascade,
  amount_cop integer not null check (amount_cop > 0),
  method text not null check (method in ('cash', 'transfer', 'card', 'other')),
  paid_at timestamptz not null default timezone('utc', now()),
  recorded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notification_queue (
  id bigint generated by default as identity primary key,
  session_id uuid not null unique references public.sessions(id) on delete cascade,
  kind text not null,
  payload jsonb not null,
  delivered_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_sessions_one_active_per_atv
  on public.sessions(atv_id)
  where status = 'active';

create index if not exists idx_sessions_status_end
  on public.sessions(status, target_end_at);

create index if not exists idx_sessions_closed_at
  on public.sessions(ended_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_atvs_updated_at on public.atvs;
create trigger trg_atvs_updated_at
before update on public.atvs
for each row
execute function public.set_updated_at();

drop trigger if exists trg_sessions_updated_at on public.sessions;
create trigger trg_sessions_updated_at
before update on public.sessions
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role public.user_role := 'operator';
begin
  if not exists(select 1 from public.profiles where role = 'admin') then
    v_role := 'admin';
  end if;

  insert into public.profiles (id, email, role)
  values (new.id, new.email, v_role)
  on conflict (id) do update
  set email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.calculate_amount_cop(
  p_base_minutes integer,
  p_base_price_cop integer,
  p_used_minutes integer
)
returns integer
language sql
immutable
as $$
  select ceil(
    (greatest(p_base_price_cop, 1)::numeric / greatest(p_base_minutes, 1)::numeric)
    * greatest(p_used_minutes, 0)::numeric
  )::integer;
$$;

create or replace function public.start_session(
  p_atv_id uuid,
  p_duration_minutes integer
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_atv public.atvs%rowtype;
  v_duration integer;
  v_session_id uuid;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;

  if p_duration_minutes is null or p_duration_minutes <= 0 then
    raise exception 'La duracion debe ser mayor que cero';
  end if;

  select * into v_atv
  from public.atvs
  where id = p_atv_id and active = true;

  if not found then
    raise exception 'La cuatrimoto no existe o esta inactiva';
  end if;

  if exists (
    select 1
    from public.sessions
    where atv_id = p_atv_id and status = 'active'
  ) then
    raise exception 'La cuatrimoto ya tiene una sesion activa';
  end if;

  v_duration := greatest(1, p_duration_minutes);

  insert into public.sessions (
    atv_id,
    started_by,
    started_at,
    target_end_at,
    status
  )
  values (
    p_atv_id,
    auth.uid(),
    timezone('utc', now()),
    timezone('utc', now()) + make_interval(mins => v_duration),
    'active'
  )
  returning id into v_session_id;

  return v_session_id;
end;
$$;

create or replace function public.stop_session(
  p_session_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.sessions%rowtype;
  v_atv public.atvs%rowtype;
  v_minutes integer;
  v_amount integer;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;

  select * into v_session
  from public.sessions
  where id = p_session_id;

  if not found then
    raise exception 'Sesion no encontrada';
  end if;

  if v_session.status <> 'active' then
    return v_session.id;
  end if;

  select * into v_atv
  from public.atvs
  where id = v_session.atv_id;

  v_minutes := ceil(extract(epoch from (timezone('utc', now()) - v_session.started_at)) / 60.0)::integer;
  v_amount := public.calculate_amount_cop(v_atv.base_minutes, v_atv.base_price_cop, v_minutes);

  update public.sessions
  set
    status = 'completed',
    ended_at = timezone('utc', now()),
    minutes_billed = v_minutes,
    amount_cop = v_amount,
    updated_at = timezone('utc', now())
  where id = v_session.id;

  return v_session.id;
end;
$$;

create or replace function public.extend_session(
  p_session_id uuid,
  p_extra_minutes integer
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.sessions%rowtype;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;

  if p_extra_minutes is null or p_extra_minutes <= 0 then
    raise exception 'Los minutos extra deben ser mayores que cero';
  end if;

  select * into v_session
  from public.sessions
  where id = p_session_id;

  if not found then
    raise exception 'Sesion no encontrada';
  end if;

  if v_session.status <> 'active' then
    raise exception 'Solo se puede extender una sesion activa';
  end if;

  update public.sessions
  set target_end_at = target_end_at + make_interval(mins => p_extra_minutes)
  where id = v_session.id;

  return v_session.id;
end;
$$;

create or replace function public.refresh_expired_sessions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := timezone('utc', now());
  v_count integer := 0;
begin
  update public.sessions
  set
    status = 'completed',
    ended_at = v_now,
    minutes_billed = ceil(extract(epoch from (v_now - started_at)) / 60.0)::integer,
    amount_cop = public.calculate_amount_cop(
      atvs.base_minutes,
      atvs.base_price_cop,
      ceil(extract(epoch from (v_now - started_at)) / 60.0)::integer
    ),
    updated_at = v_now
  from public.atvs
  where
    public.sessions.atv_id = public.atvs.id
    and public.sessions.status = 'active'
    and public.sessions.target_end_at <= v_now;

  get diagnostics v_count = row_count;

  insert into public.notification_queue (session_id, kind, payload)
  select
    s.id,
    'session_expired',
    jsonb_build_object('session_id', s.id, 'atv_id', s.atv_id, 'target_end_at', s.target_end_at)
  from public.sessions s
  where s.status = 'completed'
    and s.ended_at = v_now
  on conflict (session_id) do nothing;

  return v_count;
end;
$$;

create or replace view public.vw_finance_by_atv_today
with (security_invoker = true)
as
select
  a.id as atv_id,
  a.name as atv_name,
  count(s.id)::integer as session_count,
  coalesce(sum(s.minutes_billed), 0)::integer as minutes_total,
  coalesce(sum(s.amount_cop), 0)::integer as amount_total_cop
from public.atvs a
left join public.sessions s
  on s.atv_id = a.id
  and s.status = 'completed'
  and timezone('America/Bogota', s.ended_at)::date = timezone('America/Bogota', now())::date
group by a.id, a.name;

create or replace view public.vw_finance_total_today
with (security_invoker = true)
as
select
  count(s.id)::integer as session_count,
  coalesce(sum(s.minutes_billed), 0)::integer as minutes_total,
  coalesce(sum(s.amount_cop), 0)::integer as amount_total_cop
from public.sessions s
where
  s.status = 'completed'
  and timezone('America/Bogota', s.ended_at)::date = timezone('America/Bogota', now())::date;

alter table public.profiles enable row level security;
alter table public.atvs enable row level security;
alter table public.sessions enable row level security;
alter table public.payments enable row level security;
alter table public.notification_queue enable row level security;

drop policy if exists "Profiles select own" on public.profiles;
create policy "Profiles select own"
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Profiles update own" on public.profiles;
create policy "Profiles update own"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "ATVs select for authenticated" on public.atvs;
create policy "ATVs select for authenticated"
  on public.atvs
  for select
  to authenticated
  using (true);

drop policy if exists "ATVs insert admin" on public.atvs;
create policy "ATVs insert admin"
  on public.atvs
  for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "ATVs update admin" on public.atvs;
create policy "ATVs update admin"
  on public.atvs
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "ATVs delete admin" on public.atvs;
create policy "ATVs delete admin"
  on public.atvs
  for delete
  to authenticated
  using (public.is_admin());

drop policy if exists "Sessions select for authenticated" on public.sessions;
create policy "Sessions select for authenticated"
  on public.sessions
  for select
  to authenticated
  using (true);

drop policy if exists "Payments select for authenticated" on public.payments;
create policy "Payments select for authenticated"
  on public.payments
  for select
  to authenticated
  using (true);

drop policy if exists "Payments insert operator or admin" on public.payments;
create policy "Payments insert operator or admin"
  on public.payments
  for insert
  to authenticated
  with check (recorded_by = auth.uid() or public.is_admin());

drop policy if exists "Payments update admin" on public.payments;
create policy "Payments update admin"
  on public.payments
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Payments delete admin" on public.payments;
create policy "Payments delete admin"
  on public.payments
  for delete
  to authenticated
  using (public.is_admin());

drop policy if exists "Notification queue admin only" on public.notification_queue;
create policy "Notification queue admin only"
  on public.notification_queue
  for select
  to authenticated
  using (public.is_admin());

grant select, insert, update, delete on public.atvs to authenticated;
grant select on public.sessions to authenticated;
grant select, insert, update, delete on public.payments to authenticated;
grant select, update on public.profiles to authenticated;
grant select on public.vw_finance_by_atv_today to authenticated;
grant select on public.vw_finance_total_today to authenticated;

grant usage on schema public to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.calculate_amount_cop(integer, integer, integer) to authenticated;
grant execute on function public.start_session(uuid, integer) to authenticated;
grant execute on function public.stop_session(uuid) to authenticated;
grant execute on function public.extend_session(uuid, integer) to authenticated;
grant execute on function public.refresh_expired_sessions() to authenticated;

commit;
